source ('staSTATS.R')
source ('staMR.R')
# source ('staMRFIT.R')
source ('staCMR.R')
source ('staCMRFIT.R')
source ('staMRBN.R')
# source ('staMRFITBN.R')
source ('staCMRBN.R')
# source ('staCMRFITBN.R')
setwd ('Utility functions')
source ('staCMRx.R')
source ('gen2list.R')
source ('list2adj.R')
source ('adj2list.R')
source ('shrinkDiag.R')
source ('gen2listBN.R')
source ('staSTATSBN.R')
source ('binSTATS.R')
setwd ('../')
setwd ('java')
source ('jMR.R')
source ('jCMRx.R')
source ('jCMRBN.R')
source ('jCMRfitsx.R')
if(require("magic")==F){install.packages ("magic"); library(magic)} 
if(require("rJava")==F){install.packages ("rJava"); library(rJava)}
.jinit (classpath="fxMR-0.3.35.jar") # initialize java VM
setwd ('../')
